baseURL = "https://thewritersdaily.juliusreade.com/"
languageCode = "en-gb"
title = "The Writer's Daily"
theme = "reade"

googleAnalytics = "UA-85083093-2"

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  description = "#YOLO."
  images = ["images/logo.png"]
  title = "The Writer's Daily"
