baseURL = "https://theneverfapdeluxedaily.juliusreade.com/"
languageCode = "en-gb"
title = "The NeverFap Deluxe Daily"
theme = "reade"

googleAnalytics = "UA-85083093-2"

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  description = "#YOLO."
  images = ["images/tndd/logo_512.png"]
  title = "The NeverFap Deluxe Daily"

[markup.goldmark.renderer]
  unsafe= true